name = "pos-api1"
main = "src/index.js"
compatibility_date = "2024-11-01"
compatibility_flags = ["nodejs_compat"]

# Ganti database_id dengan ID D1 database kamu sendiri
# (didapat setelah menjalankan: wrangler d1 create gymbooking-db)
[[d1_databases]]
binding = "DB"
database_name = "gymbooking-db"
database_id = "a6511388-d37f-458f-a65a-20ad5be3ef85"

[vars]
JWT_SECRET = RAHASIA_NEGARA_POS_API_2026_!#$
CLIENT_ORIGIN = "*"
